// Public allowlist only. Never add account totals, share counts, dollar returns,
// transaction sizes, aggregate cost basis, or brokerage source files here.
// Weights are rounded editorial snapshots, not computed from account amounts.
export const holdings = [
  {
    ticker: 'CRDO',
    name: 'Credo Technology',
    sector: 'Connectivity',
    weight: 33,
    entry: 160.82,
    snapshot: 168.25,
    color: '#566c50',
  },
  {
    ticker: 'BMNR',
    name: 'BitMine Immersion',
    sector: 'Digital assets',
    weight: 28,
    entry: 26.97,
    snapshot: 23.89,
    color: '#b77552',
  },
  {
    ticker: 'COIN',
    name: 'Coinbase',
    sector: 'Digital assets',
    weight: 14,
    entry: 245.35,
    snapshot: 173.97,
    color: '#c7a65d',
  },
  {
    ticker: 'AMD',
    name: 'Advanced Micro Devices',
    sector: 'Semiconductors',
    weight: 9,
    entry: 157.0,
    snapshot: 545.09,
    color: '#7c8b9c',
  },
  {
    ticker: 'NVDA',
    name: 'NVIDIA',
    sector: 'Semiconductors',
    weight: 6,
    entry: 139.17,
    snapshot: 219.34,
    color: '#a5b394',
  },
  {
    ticker: 'CMG',
    name: 'Chipotle Mexican Grill',
    sector: 'Restaurants',
    weight: 5,
    entry: 44.37,
    snapshot: 33.51,
    color: '#b9a28f',
  },
  {
    ticker: 'GOOG',
    name: 'Alphabet',
    sector: 'Internet services',
    weight: 4,
    entry: 366.24,
    snapshot: 343.68,
    color: '#817767',
  },
  {
    ticker: 'HOOD',
    name: 'Robinhood',
    sector: 'Brokerage',
    weight: 1,
    entry: 97.58,
    snapshot: 109.81,
    color: '#d1c5a5',
  },
] as const;
